version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: resume_bot
    volumes:
      - mongo_data:/data/db

  mongo_express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_PASSWORD}"
      ME_CONFIG_OPTIONS_EDITORTHEME: "dracula"
    ports:
      - "8081:8081"

#   bot:
#     build: .
#     depends_on:
#       - mongo
#     restart: unless-stopped
#     environment:
#       TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
#       MONGO_DSN: "mongodb://mongo:27017/resume_bot"
#       DB_NAME: "resume_bot"
#       DATA_DIR: "/data/uploads"
#       SENTRY_DSN: "${SENTRY_DSN}"
#       USER_AGREEMENT_URL: "${USER_AGREEMENT_URL}"
#       PRIVACY_URL: "${PRIVACY_URL}"
#       FREE_ONE_TIME_FULL: "1"
#       LLM_BASE_URL: "${LLM_BASE_URL}"
#       LLM_API_KEY: "${LLM_API_KEY}"
#       LLM_MODEL_NAME: "${LLM_MODEL_NAME}"
#     volumes:
#       - ./data:/data
#     ports:
#       - "8000:8000"

volumes:
  mongo_data:
